  import {
  Brain,
  FileText,
  Calculator,
  Lightbulb,
  BookOpen,
  NetworkIcon as Connection,
  ArrowRightLeft,
  Puzzle,
  GanttChart,
  Pencil,
  ActivityIcon as Function,
  Shapes,
  PieChart,
} from "lucide-react"

  export const readingDomains = [
    {
      name: "Information and Ideas",
      distribution: "≈26%",
      questions: "12-14 questions",
      skills: [
        {
          name: "Central Ideas and Details",
          icon:
 <Brain size={20} color="#4f46e5" />,
          needsPractice: false,
          accuracy: 82,
          lastPracticed: "2 days ago",
          progress: 82,
          description: "Students will determine the central idea of a text and/or interpret the key details supporting that idea.",
        },
        {
          name: "Command of Evidence (Textual)",
          icon: <FileText size={20} color="#ef4444" />,
          needsPractice: true,
          accuracy: 65,
          lastPracticed: "4 days ago",
          progress: 65,
          description: "Students will determine the textual evidence that best supports a specified claim or point.",
        },
        {
          name: "Command of Evidence (Quantitative)",
          icon: <Calculator size={20} color="#f59e0b" />,
          needsPractice: true,
          accuracy: 70,
          lastPracticed: "3 days ago",
          progress: 70,
          description: "Students will determine the quantitative evidence that best supports a specified claim or point.",
        },
        {
          name: "Inferences",
          icon: <Lightbulb size={20} color="#10b981" />,
          needsPractice: false,
          accuracy: 78,
          lastPracticed: "1 day ago",
          progress: 78,
          description: "Students will draw reasonable inferences based on explicit and/or implicit information and ideas in a text.",
        },
      ],
    },
    {
      name: "Craft and Structure",
      distribution: "≈28%",
      questions: "13-15 questions",
      skills: [
        {
          name: "Words in Context",
          icon: <BookOpen size={20} color="#8b5cf6" />,
          needsPractice: false,
          accuracy: 85,
          lastPracticed: "2 days ago",
          progress: 85,
          description: "Students will determine the meaning of a high-utility academic word or phrase in context or use such vocabulary in a contextually appropriate way.",
        },
        {
          name: "Text Structure and Purpose",
          icon: <GanttChart size={20} color="#ec4899" />,
          needsPractice: true,
          accuracy: 68,
          lastPracticed: "5 days ago",
          progress: 68,
          description: "Students will analyze the structure of a text or determine the main rhetorical purpose of a text.",
        },
        {
          name: "Cross-Text Connections",
          icon: <Connection size={20} color="#14b8a6" />,
          needsPractice: false,
          accuracy: 75,
          lastPracticed: "3 days ago",
          progress: 75,
          description: "Students will draw reasonable connections between two texts on related topics.",
        },
      ],
    },
    {
      name: "Expression of Ideas",
      distribution: "≈20%",
      questions: "8-12 questions",
      skills: [
        {
          name: "Rhetorical Synthesis",
          icon: <Puzzle size={20} color="#f43f5e" />,
          needsPractice: true,
          accuracy: 72,
          lastPracticed: "4 days ago",
          progress: 72,
          description: "Students will strategically integrate information and ideas on a topic to form an effective sentence achieving a specified rhetorical aim.",
        },
        {
          name: "Transitions",
          icon: <ArrowRightLeft size={20} color="#06b6d4" />,
          needsPractice: false,
          accuracy: 80,
          lastPracticed: "2 days ago",
          progress: 80,
          description: "Students will determine the most effective transition word or phrase to logically connect information and ideas in a text.",
        },
      ],
    },
    {
      name: "Standard English Conventions",
      distribution: "≈26%",
      questions: "11-15 questions",
      skills: [
        {
          name: "Boundaries",
          icon: <Connection size={20} color="#8b5cf6" />,
          needsPractice: true,
          accuracy: 70,
          lastPracticed: "3 days ago",
          progress: 70,
          description: "Students will use contextually appropriate punctuation to properly mark the end of a sentence.",
        },
        {
          name: "Form, Structure, and Sense",
          icon: <Pencil size={20} color="#ef4444" />,
          needsPractice: false,
          accuracy: 88,
          lastPracticed: "1 day ago",
          progress: 88,
          description: "Students will ensure agreement in number between a subject and a verb.",
        },
      ],
    },
  ]
